<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://soap.sforce.com/2005/09/outbound"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://soap.sforce.com/2005/09/outbound"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="SOAPService">
        <plnk:role name="NotificationPort" portType="tns:NotificationPort"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soap.sforce.com/2005/09/outbound" location="harish_outbound.wsdl"/>
</wsdl:definitions>
